import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'
import HomeSection from './HomeSection'
import Destination from './Destination'
import Nav from '../components/Nav'
import Sidebar from '../components/Sidebar'
import Technology from '../pages/Technology'
import Crew from '../pages/Crew'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Bellefair&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&display=swap"
          rel="stylesheet"
        ></link>
        {/* <link rel="stylesheet" href="" /> */}
      </Head>
      <Nav />
      <main>
        {/* <HomeSection /> */}
        <Sidebar />
        {/* <Destination /> */}
        {/* <Technology /> */}
        <Crew />
      </main>
    </>
  )
}
