import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'
import HomeSection from './HomeSection'
import Destination from './Destination'
import Nav from '../components/Nav'
import Sidebar from '../components/Sidebar'
import Technology from '../pages/Technology'
import Crew from '../pages/Crew'
import React, { useState, useEffect, useContext } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { setData, setPlanets, setCurrPlanet }: any = useContext(PlanetsContext)
  useEffect(() => {
    fetch('../../data.json')
      .then((response) => response.json())
      .then((data) => {
        setData(data)
        setPlanets(data.map((planet) => planet.name))
        setCurrPlanet('Mercury')
      })
  }, [])

  // const {
  //   name,
  //   overview,
  //   structure,
  //   geology,
  //   rotation,
  //   revolution,
  //   radius,
  //   temperature,
  //   images,
  // } = planet;

  const changePlanet = (currPlanet: String) => {
    const { name, images, description, travel } = destination

    const { name, images, role, bio } = crew

    const { name, images, description } = technology

    if (name === currPlanet) {
      setCurrPlanet(name)
      setData()
      setPlanets()
      setCrew()
      setTechnology()
    }
  }

  // when name is chosen

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Bellefair&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&display=swap"
          rel="stylesheet"
        ></link>
        {/* <link rel="stylesheet" href="" /> */}
      </Head>
      <Nav />
      <main>
        {/* <HomeSection /> */}
        <Sidebar />
        {/* <Destination /> */}
        {/* <Technology /> */}
        <Crew />
      </main>
    </>
  )
}
